# Generated by Django 2.0 on 2020-04-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.IntegerField(choices=[(0, 'head_para_bold'), (1, 'head_para'), (2, 'heading_large'), (3, 'heading_smaill'), (4, 'para'), (5, 'quote'), (6, 'code'), (7, 'list')])),
                ('blog_type', models.IntegerField(choices=[(0, 'standard'), (1, 'video'), (2, 'audio')])),
                ('content', models.CharField(max_length=2000)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='Blog.Blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='Blog.Tags'),
        ),
    ]
