# Generated by Django 2.0 on 2020-04-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='element_type',
            field=models.IntegerField(choices=[(0, 'head_para_bold'), (1, 'head_para'), (2, 'heading_large'), (3, 'heading_smaill'), (4, 'para'), (5, 'quote'), (6, 'code'), (7, 'list'), (8, 'image')]),
        ),
    ]
