# Generated by Django 2.0 on 2020-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200405_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='thumb',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
