# Generated by Django 3.0.5 on 2020-04-09 02:09

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogs_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=500)),
                ('thumb', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='username',
        ),
        migrations.AddField(
            model_name='blogs',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Elements',
        ),
        migrations.AddField(
            model_name='blogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='Blog.User'),
        ),
    ]
