# Generated by Django 3.0.5 on 2020-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20200409_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='thumb',
            field=models.CharField(max_length=200),
        ),
    ]
